import numpy as np
import cvxpy as cp
from scipy.optimize import minimize
from sklearn.base import BaseEstimator
from quack.quantifiers.base import QuantifierMixin


class HDx(BaseEstimator, QuantifierMixin):
  """
  HDx (Hellinger Distance on Features X).
  
  This method do not use any supervised classifier. It estimates the prevalences
  minimizing the Hellinger Distance between feature histograms for training and
  test sets.
  
  Refs
  [1] Víctor González-Castro, Rocío Alaiz-Rodríguez, and Enrique Alegre.
      Class distribution estimation based on the Hellinger distance.
      Information Sciences, 218(1):146-164, 2013.

  """
  def __init__(self, n_bins: int = 10):
    self.n_bins = n_bins

  def fit(self, X: np.ndarray, y: np.ndarray):
    """
    Create profiles for each attribute/feature per class.
    As raw features can have totally different range of values, HDx calculate and
    save the bins limits specifics for each feature.
    """
    self.classes_ = np.unique(y)
    self.n_classes_ = len(self.classes_)
    self.n_features_ = X.shape[1]
    
    # save the original prevalence in case of optimizer failure
    _, counts = np.unique(y, return_counts=True)
    self.train_prevalence_ = counts / np.sum(counts)

    # structure to save bins and profiles for training
    self.bin_edges_per_feature_ = []
    
    # profile matrix (n_classes, n_features, n_bins)
    self.profiles_ = np.zeros((self.n_classes_, self.n_features_, self.n_bins))

    # loop each feature in the data individually
    for f in range(self.n_features_):
      feature_vector = X[:, f]
      # define the limits for each bins based on the min and max global for that feature
      bin_edges = np.linspace(feature_vector.min(), feature_vector.max(), self.n_bins + 1)
      self.bin_edges_per_feature_.append(bin_edges)

      # build the calibration histogram for each class in that feature
      for c_idx, c in enumerate(self.classes_):
        feature_c = feature_vector[y == c]
        
        h, _ = np.histogram(feature_c, bins=bin_edges)
        # normalization, transform each count in discrete density of probabilities
        self.profiles_[c_idx, f, :] = h / (np.sum(h) + 1e-12)

    return self

  def predict(self, X: np.ndarray) -> np.ndarray:
    """
    Align the test and optimize the Hellinger Distance
    """
    # extract the profiles for test bag using bins saved in training phase
    test_histograms = np.zeros((self.n_features_, self.n_bins))
    for f in range(self.n_features_):
      h, _ = np.histogram(X[:, f], bins=self.bin_edges_per_feature_[f])
      test_histograms[f, :] = h / (np.sum(h) + 1e-12)
    
    # objective function: cum hellinger distance
    def hellinger_objective(alpha):
      total_distance = 0.0
      # loop each feature calculating the divergence
      for f in range(self.n_features_):
        # linear mixture for distributions for feature f given the actual alpha
        # same as: (alpha_0 * H_0) + (alpha_1 * H_1) + ...
        mixture_f = np.zeros(self.n_bins)
        for c_idx in range(self.n_classes_):
          mixture_f += alpha[c_idx] * self.profiles_[c_idx, f, :]
        # avoid negative values before sqrt
        mixture_f = np.maximum(mixture_f, 0.0)
        # hellinger distance formula between test and the estimated mixture
        h_test_f = test_histograms[f, :]
        feature_dist = 0.5 * np.sum((np.sqrt(h_test_f) - np.sqrt(mixture_f)) ** 2)
        total_distance += feature_dist
          
      return total_distance

    # restrictions: sum of prevalences must be 1
    constraints = ({'type': 'eq', 'fun': lambda alpha: np.sum(alpha) - 1.0})
    
    # boundaries: none prevalence must be less than 0 or greater than 1
    bounds = [(0.0, 1.0) for _ in range(self.n_classes_)]
    
    # initial prediction: uniform distribution
    initial_guess = np.ones(self.n_classes_) / self.n_classes_

    # solver SLSQP (Sequential Least Squares Programming)
    result = minimize(
      hellinger_objective, 
      initial_guess, 
      method='SLSQP', 
      bounds=bounds, 
      constraints=constraints
    )

    if not result.success:
      return self.train_prevalence_.copy()

    p_adjusted = result.x
    # avoid floating points errors or noise
    p_adjusted = np.clip(p_adjusted, 0.0, 1.0)
    p_adjusted /= np.sum(p_adjusted)

    return p_adjusted


class ReadMe(BaseEstimator, QuantifierMixin):
  """
  ReadMe.
  
  Model minimizes the sum of square errors (L2) between the features
  histogram vector generated by test bags and the linear combination
  of train matrices used in calibration.
  
  Refs
    [1] Daniel J. Hopkins and Gary King. A method of automated
        nonparametric content analysis for social science.
        American Journal of Political Science, 54(1):229-247, 2010.

  """
  def __init__(self, n_bins=10):
    self.n_bins = n_bins

  def fit(self, X: np.ndarray, y: np.ndarray):
    """
    Build the calibration matrix (M).
    Merge all dimensions of features and bins in a unique continuous vector
    for each class, avoiding loops in optimization.
    """
    self.classes_ = np.unique(y)
    self.n_classes_ = len(self.classes_)
    self.n_features_ = X.shape[1]
    
    # fallback with training prevalence
    _, counts = np.unique(y, return_counts=True)
    self.train_prevalence_ = counts / np.sum(counts)

    # save the bins calculated in training phase for each feature
    self.bin_edges_per_feature_ = []
    
    calib_cols = [] # histograms for each class

    # first-step
    # extract the limits for each feature bins
    for f in range(self.n_features_):
      feature_vector = X[:, f]
      bin_edges = np.linspace(feature_vector.min(), feature_vector.max(), self.n_bins + 1)
      self.bin_edges_per_feature_.append(bin_edges)

    # second-step
    # build the profile per class
    for c_idx, c in enumerate(self.classes_):
      X_c = X[y == c]
      class_components = []
      
      for f in range(self.n_features_):
        h, _ = np.histogram(X_c[:, f], bins=self.bin_edges_per_feature_[f])
        # local normalization per feature
        h = h / (np.sum(h) + 1e-12)
        class_components.append(h)
      
      # Concatenate all feature histograms for that class in an unique array
      # with shape (n_features * n_bins,)
      super_vector_c = np.concatenate(class_components)
      calib_cols.append(super_vector_c)

    # Monta a matriz M. Tamanho: (n_features * n_bins, n_classes)
    # build the matrix M
    self.calib_matrix_ = np.column_stack(calib_cols)
    return self

  def predict(self, X: np.ndarray) -> np.ndarray:
    """
    """
    test_components = []
    # build the test bag vector using the training format
    for f in range(self.n_features_):
      h, _ = np.histogram(X[:, f], bins=self.bin_edges_per_feature_[f])
      h = h / (np.sum(h) + 1e-12)
      test_components.append(h)
  
    # continuous vector observed in test (n_features * n_bins,)
    h_test = np.concatenate(test_components)
    # alpha is the decision vector containing all real prevalences (n_classes,)
    alpha = cp.Variable(self.n_classes_)

    # ReadMe minimizes the L2 error in histograms: || h_test - M @ alpha ||^2
    objective = cp.Minimize(cp.sum_squares(h_test - self.calib_matrix_ @ alpha))
    constraints = [cp.sum(alpha) == 1, alpha >= 0]

    problem = cp.Problem(objective, constraints)
    problem.solve()

    p_adjusted = alpha.value
    if p_adjusted is None:
      return self.train_prevalence_.copy()

    p_adjusted = np.clip(p_adjusted, 0.0, 1.0)
    p_adjusted /= np.sum(p_adjusted)

    return p_adjusted
